"""Add foreign key to finding

Revision ID: a1fc1f32e4c9
Revises: 
Create Date: 2026-03-01 02:21:32.048211
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1fc1f32e4c9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_threads',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('github_comment_id', sa.BigInteger(), nullable=False),
    sa.Column('finding_id', sa.UUID(), nullable=True),
    sa.Column('repo_id', sa.BigInteger(), nullable=True),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('thread_state', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_comment_id')
    )
    op.create_index('ix_conversation_threads_github_comment_id', 'conversation_threads', ['github_comment_id'], unique=True)
    op.create_table('installations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_login', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pr_reviews',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('repo_id', sa.BigInteger(), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('pr_title', sa.Text(), nullable=True),
    sa.Column('head_sha', sa.String(length=40), nullable=True),
    sa.Column('base_sha', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=True),
    sa.Column('findings_count', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pr_reviews_repo_pr', 'pr_reviews', ['repo_id', 'pr_number'], unique=False)
    op.create_index('ix_pr_reviews_status', 'pr_reviews', ['status'], unique=False)
    op.create_table('repositories',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('installation_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=500), nullable=False),
    sa.Column('default_branch', sa.String(length=255), nullable=False),
    sa.Column('index_status', sa.String(length=50), nullable=False),
    sa.Column('last_indexed_sha', sa.String(length=40), nullable=True),
    sa.Column('indexed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_repositories_full_name', 'repositories', ['full_name'], unique=False)
    op.create_index('ix_repositories_installation_id', 'repositories', ['installation_id'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('line_start', sa.Integer(), nullable=True),
    sa.Column('line_end', sa.Integer(), nullable=True),
    sa.Column('diff_position', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('suggestion_code', sa.Text(), nullable=True),
    sa.Column('github_comment_id', sa.BigInteger(), nullable=True),
    sa.Column('was_applied', sa.Boolean(), nullable=True),
    sa.Column('was_dismissed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['pr_reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_findings_review_id', 'findings', ['review_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_findings_review_id', table_name='findings')
    op.drop_table('findings')
    op.drop_index('ix_repositories_installation_id', table_name='repositories')
    op.drop_index('ix_repositories_full_name', table_name='repositories')
    op.drop_table('repositories')
    op.drop_index('ix_pr_reviews_status', table_name='pr_reviews')
    op.drop_index('ix_pr_reviews_repo_pr', table_name='pr_reviews')
    op.drop_table('pr_reviews')
    op.drop_table('installations')
    op.drop_index('ix_conversation_threads_github_comment_id', table_name='conversation_threads')
    op.drop_table('conversation_threads')
    # ### end Alembic commands ###
